### ISSUE TITLE
Could this be a script-only package?

### ISSUE THREAD

**Issue by awelzel** [zeek-plugins/mdns#1]
Hey,

not necessarily an issue, but mostly wondering if this repo could be made a Zeek package (script-only) rather than a Zeek plugin (containing C++ code and requiring compilation during installation) as is now?

All the logic seems to be script-based here:
https://github.com/zeek-plugins/mdns/blob/main/scripts/events.zeek

Unless you're planning functionality implemented with C++, it may make sense to make this script-only so it can be installed even when no compiler is available.

**Comment by fdekeers** [comment]
Hi,

Thanks for the advice. Indeed, in its current form, it could be a script-only package.
To be honest, I did not know this specific flavor existed.
I will check on how to do the conversion.

**Comment by fdekeers** [comment]
Hi again,

Since the plugin defines new events (`mdns_*`), doesn't it still need those events to be defined in a bif file, and thus need compilation ?
Or is it a way to define events without a bif file ?

**Comment by awelzel** [comment]
> Hi again,
> 
> Since the plugin defines new events (`mdns_*`), doesn't it still need those events to be defined in a bif file, and thus need compilation ? Or is it a way to define events without a bif file ?

You don't need the bif file, you can declare events in a plain `.zeek` file as well.

```
# Declare a new event
global mdns_message: event(x: string);

event zeek_init()
        {
        event mdns_message("test");
        }

# Module using mdns_message()
module Test;
event mdns_message(x: string)
        {
        print "Handler for mdns_message", x;
        }
```

See also: https://docs.zeek.org/en/master/script-reference/types.html#event

**Comment by fdekeers** [comment]
Thanks a lot, I implemented your comment, the package is now script only.
